spring.profiles.active=h2

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# Logging
logging.level.root=WARN
logging.level.org.springframework.batch=INFO
logging.level.de.fi.tag2_07partitionierer=DEBUG

spring.main.banner-mode=off
